namespace: knightsg
name: dkron
version: 0.1.2
readme: README.md
authors:
  - Guy Knights <contact@guyknights.com>
description: Installation, configuration and management of a Dkron cluster
license:
  - GPL-2.0-or-later
tags:
  - dkron
dependencies: {}
repository: https://github.com/knightsg/dkron
documentation: ''
homepage: ''
issues: 'https://github.com/knightsg/dkron/issues'
build_ignore:
  - 'env'
  - 'env/*'
  - 'hosts.yml'
  - 'ansible.cfg'