all:
  hosts:
    dkron1:
      ansible_host: 192.168.20.5 
      ansible_port: 2201
    dkron2:
      ansible_host: 192.168.20.5 
      ansible_port: 2202
    dkron3:
      ansible_host: 192.168.20.5 
      ansible_port: 2203
  vars:
    ansible_port: 2200
    ansible_user: ansible
    become: yes