all:
  hosts:
    dkron1:
      ansible_host: 192.168.20.5 
      ansible_port: 2201
    dkron2:
      ansible_host: 192.168.20.5 
      ansible_port: 2202
    dkron3:
      ansible_host: 192.168.20.5 
      ansible_port: 2203
  vars:
    ansible_port: 2200
    ansible_user: ansible
    ansible_password: today123
    become: yes
    ansible_python_interpreter: /usr/bin/python3
    containerized: True

  children:
    dkron:
      hosts:
        dkron1:
        dkron2:
        dkron3: