all:
  hosts:
    dkron1:
      ansible_host: 54.218.134.87
    dkron2:
      ansible_host: 52.12.230.186
  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: ~/.ssh/personal.pem
    become: yes
    ansible_python_interpreter: /usr/bin/python3
    containerized: False

  children:
    dkron:
      hosts:
        dkron1:
        dkron2: