all:
  hosts:
    dkron1:
      ansible_host: 192.168.20.11
    dkron2:
      ansible_host: 192.168.20.12
    dkron3:
      ansible_host: 192.168.20.13
  vars:
    ansible_user: localuser
    ansible_ssh_pass: password
    ansible_become_pass: password
    become: yes
    ansible_python_interpreter: /usr/bin/python3
    containerized: False

  children:
    dkron:
      hosts:
        dkron1:
        dkron2:
        dkron3: