---
# tasks file for dkron-cluster

- name: map nodes in dkron group to ordered list
  set_fact:
    dkron_hosts: "{{ dkron_hosts|default([]) + [hostvars[item]['ansible_default_ipv4']['address']] }}"
  loop: "{{ groups['dkron'] }}"
    
- name: create dkron config file for clustering
  copy:
    content: |
      server: true
      bootstrap-expect: {{ dkron_hosts | length }}
      join: 
        {{ dkron_hosts | sort | difference([hostvars[inventory_hostname]['ansible_default_ipv4']['address']]) | to_nice_yaml | trim | indent(2) }}
    dest: /etc/dkron/dkron.yml
  notify:
  - restart dkron