---
# tasks file for dkron-cluster

- import_tasks: repo.yml
- import_tasks: install.yml
- import_tasks: config.yml
- import_tasks: service.yml

- name: test dkron_cluster_info module
  dkron_cluster_info:
    endpoint: 192.168.20.5
    port: 8081
  register: cluster_info

- debug:
    var: cluster_info