---
# tasks file for dkron_cluster
- name: configure dkron apt repository
  ansible.builtin.apt_repository:
    repo: deb [trusted=yes] https://repo.distrib.works/apt/ /
    filename: dkron
    update_cache: yes
    state: present

- name: install dkron (autoupgrade)
  ansible.builtin.apt:
    name: dkron
    state: latest
  when: 
    - autoupgrade == True
  notify:
    - restart dkron

- name: install dkron (current version)
  ansible.builtin.apt:
    name: dkron
    state: present
  when: 
    - autoupgrade == False
    - version is not defined

- name: install dkron (specific version)
  ansible.builtin.apt:
    name: "dkron={{ version }}"
    state: present
    force: yes # allow downgrades
  when:
    - autoupgrade == False
    - version is defined
    - version is regex("[\d]+\.[\d]+\.[\d]+")
  notify:
    - restart dkron