---
# tasks file for dkron_cluster

- name: configure dkron apt repository
  apt_repository:
    repo: deb [trusted=yes] https://repo.distrib.works/apt/ /
    filename: dkron
    update_cache: yes
    state: present