---
# tasks file for dkron_cluster
- name: install dkron (autoupgrade)
  ansible.builtin.package:
    name: dkron
    state: latest
  when: 
    - autoupgrade is defined
    - autoupgrade == True
  notify:
    - restart dkron

- name: install dkron (current version)
  ansible.builtin.package:
    name: dkron
    state: present
  when: 
    - autoupgrade is not defined or autoupgrade == False
    - version is not defined

- name: install dkron (specific version)
  ansible.builtin.package:
    name: "dkron={{ version }}"
    state: present
  when: 
    - autoupgrade is not defined or autoupgrade == False
    - version is defined
    - version is regex("[\d]+\.[\d]+\.[\d]+")
  notify:
    - restart dkron

- ansible.builtin.fail:
    msg: "Unable to install dkron package, supplied version is invalid."
  when:
    - autoupgrade is not defined or autoupgrade == False
    - version is defined
    - version is not regex("[\d]+\.[\d]+\.[\d]+")