---
# Set up dkron cluster and return cluster information

- hosts: all
  
  roles:
    - role: dkron-cluster
      vars:
        autoupgrade: False
        version: 3.0.8

- hosts: localhost
  gather_facts: False
  collections:
    - knightsg.dkron

  tasks:

    - name: gather cluster information
      dkron_cluster_info:
        endpoint: "{{ groups['dkron']|map('extract', hostvars, ['ansible_host'])|first }}"
        type: jobs
      register: task_output

    - name: display cluster information
      debug:
        var: task_output.ansible_module_results