---
# Return detailed job information

- hosts: localhost
  gather_facts: False
  collections:
    - knightsg.dkron
  vars:
    query_host: "{{ groups['dkron']|map('extract', hostvars, ['ansible_host'])|first }}"
    
  tasks:

    - name: test dkron_job_info module
      dkron_job_info:
        endpoint: "{{ query_host }}"
        job_names:
          - job2
          - job7
        limit_history: 5
      register: task_output

    - name: display cluster job info
      debug:
        var: task_output