---
# Create/update a job and display the returned job configuration for reference

- hosts: localhost
  gather_facts: False
  collections:
    - knightsg.dkron
  vars:
    query_host: "{{ groups['dkron']|map('extract', hostvars, ['ansible_host'])|first }}"
    
  tasks:

    - name: test dkron_job module by creating a job
      dkron_job:
        endpoint: "{{ query_host }}"
        job_name: job8
        schedule: '@every 1m'
        file_processor:
          log_dir: /tmp
        shell_executor:
          command: '/bin/true'
        overwrite: True
      register: task_output

    - name: display job config
      debug:
        var: task_output