---
# A playbook for debugging and testing

- hosts: localhost
  gather_facts: False
  collections:
    - knightsg.dkron
  vars:
    query_host: "{{ groups['all']|map('extract', hostvars, ['ansible_host'])|first }}"

  tasks:

    - name: test cluster_info module
      dkron_cluster_info:
        endpoint: "{{ query_host }}"
        type: all
      register: task_output

    # - name: test job_info module
    #   dkron_job_info:
    #     endpoint: "{{ query_host }}"
    #     limit_history: 1
    #   register: task_output

    # - name: test job module
    #   dkron_job:
    #     endpoint: "{{ query_host }}"
    #     name: mydumbtestjob1
    #     owner: 'Guy Knights'
    #     shell_executor:
    #       command: "echo 'my test command output'"
    #     state: present
    #   register: task_output

    - name: display output
      debug:
        var: task_output
