---
# A playbook for debugging and testing

- hosts: all
  gather_facts: True
  collections:
    - knightsg.dkron
  vars:
    query_host: "{{ groups['dkron']|map('extract', hostvars, ['ansible_host'])|first }}"
    
  roles:
    - role: dkron_cluster
