---
# test playbook for dkron collection

- hosts: all
  collections:
    - knightsg.dkron
  
  roles:
    - role: dkron-cluster
      vars:
        autoupgrade: True

  tasks:

    - name: test dkron_cluster_info module
      dkron_cluster_info:
        endpoint: "{{ groups['dkron']|map('extract', hostvars, ['ansible_host'])|first }}"
        type: leader
      register: data

    # - name: test dkron_job_info module
    #   dkron_job_info:
    #     endpoint: "{{ groups['dkron']|map('extract', hostvars, ['ansible_host'])|first }}"
    #     job_name: testjob
    #   register: data

    - debug:
        var: data