---
# test playbook for dkron collection

- hosts: all
  
  roles:
    - role: dkron-cluster
      vars:
        autoupgrade: True

- hosts: localhost
  gather_facts: False
  collections:
    - knightsg.dkron

  tasks:

    # - name: test dkron_cluster_info module
    #   dkron_cluster_info:
    #     endpoint: "{{ groups['dkron']|map('extract', hostvars, ['ansible_host'])|first }}"
    #     type: jobs
    #   register: data

    - name: test dkron_job_info module
      dkron_job_info:
        endpoint: "{{ groups['dkron']|map('extract', hostvars, ['ansible_host'])|first }}"
        names: job
      register: data

    - debug:
        var: data